In [19]:
run_query("03_average_ticket.sql")

   TicketMedio
0    3915.9951

In [18]:
run_query("02_orders.sql")

   TotalPedidos
0         31465

In [17]:
from query_executor import run_query

df = run_query("01_revenue.sql")

df

   ReceitaTotal
0  1.232168e+08