In [14]:
print("Receita Total")
display(revenue)

print()

print("Quantidade de Pedidos")
display(orders)

print()

print("Ticket Médio")
display(average_ticket)

Receita Total

   ReceitaTotal
0  1.232168e+08

Quantidade de Pedidos

   TotalPedidos
0         31465

Ticket Médio

   TicketMedio
0    3915.9951

In [13]:
for name, df in datasets.items():

    print("=" * 80)
    print(name)

    display(df.isna().sum())

================================================================================
Revenue

ReceitaTotal    0
dtype: int64

================================================================================
Orders

TotalPedidos    0
dtype: int64

================================================================================
Average Ticket

TicketMedio    0
dtype: int64

================================================================================
Sales Over Time

Ano        0
Receita    0
dtype: int64

================================================================================
Top Customers

CustomerID      0
SalesOrderID    0
TotalDue        0
dtype: int64

================================================================================
Top Products

ProductID    0
Receita      0
dtype: int64

In [12]:
for name, df in datasets.items():

    print("=" * 80)
    print(name)

    display(df.describe(include="all"))

================================================================================
Revenue

       ReceitaTotal
count  1.000000e+00
mean   1.232168e+08
std             NaN
min    1.232168e+08
25%    1.232168e+08
50%    1.232168e+08
75%    1.232168e+08
max    1.232168e+08

================================================================================
Orders

       TotalPedidos
count           1.0
mean        31465.0
std             NaN
min         31465.0
25%         31465.0
50%         31465.0
75%         31465.0
max         31465.0

================================================================================
Average Ticket

       TicketMedio
count       1.0000
mean     3915.9951
std            NaN
min      3915.9951
25%      3915.9951
50%      3915.9951
75%      3915.9951
max      3915.9951

================================================================================
Sales Over Time

               Ano       Receita
count     4.000000  4.000000e+00
mean   2012.500000  3.080420e+07
std       1.290994  1.554070e+07
min    2011.000000  1.415570e+07
25%    2011.750000  2.035355e+07
50%    2012.500000  3.004760e+07
75%    2013.250000  4.049825e+07
max    2014.000000  4.896589e+07

================================================================================
Top Customers

         CustomerID  SalesOrderID       TotalDue
count  31465.000000  31465.000000   31465.000000
mean   20170.175687  59391.000000    3915.995109
std     6261.728960   9083.307446   12515.462713
min    11000.000000  43659.000000       1.518300
25%    14432.000000  51525.000000      62.951900
50%    19452.000000  59391.000000     865.204000
75%    25994.000000  67257.000000    2615.490800
max    30118.000000  75123.000000  187487.825000

================================================================================
Top Products

        ProductID       Receita
count  266.000000  2.660000e+02
mean   857.639098  4.129563e+05
std     84.860270  7.031786e+05
min    707.000000  1.627200e+02
25%    783.250000  2.814164e+04
50%    863.500000  1.175707e+05
75%    931.750000  4.699232e+05
max    999.000000  4.400593e+06

In [11]:
for name, df in datasets.items():

    print("=" * 80)
    print(name)

    df.info()

================================================================================
Revenue
<class 'pandas.DataFrame'>
RangeIndex: 1 entries, 0 to 0
Data columns (total 1 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   ReceitaTotal  1 non-null      float64
dtypes: float64(1)
memory usage: 140.0 bytes
================================================================================
Orders
<class 'pandas.DataFrame'>
RangeIndex: 1 entries, 0 to 0
Data columns (total 1 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   TotalPedidos  1 non-null      int64
dtypes: int64(1)
memory usage: 140.0 bytes
================================================================================
Average Ticket
<class 'pandas.DataFrame'>
RangeIndex: 1 entries, 0 to 0
Data columns (total 1 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   TicketMedio  1 non-null      float64
dtypes: float64(1)
memory usage: 140.0 bytes
================================================================================
Sales Over Time
<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Ano      4 non-null      int64
 1   Receita  4 non-null      float64
dtypes: float64(1), int64(1)
memory usage: 196.0 bytes
================================================================================
Top Customers
<class 'pandas.DataFrame'>
RangeIndex: 31465 entries, 0 to 31464
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   CustomerID    31465 non-null  int64
 1   SalesOrderID  31465 non-null  int64
 2   TotalDue      31465 non-null  float64
dtypes: float64(1), int64(2)
memory usage: 737.6 KB
================================================================================
Top Products
<class 'pandas.DataFrame'>
RangeIndex: 266 entries, 0 to 265
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   ProductID  266 non-null    int64
 1   Receita    266 non-null    float64
dtypes: float64(1), int64(1)
memory usage: 4.3 KB

In [10]:
for name, df in datasets.items():

    print("=" * 80)
    print(name)

    display(df.head())

================================================================================
Revenue

   ReceitaTotal
0  1.232168e+08

================================================================================
Orders

   TotalPedidos
0         31465

================================================================================
Average Ticket

   TicketMedio
0    3915.9951

================================================================================
Sales Over Time

    Ano       Receita
0  2011  1.415570e+07
1  2012  3.767570e+07
2  2013  4.896589e+07
3  2014  2.241950e+07

================================================================================
Top Customers

   CustomerID  SalesOrderID    TotalDue
0       29825         43659  23153.2339
1       29672         43660   1457.3288
2       29734         43661  36865.8012
3       29994         43662  32474.9324
4       29565         43663    472.3108

================================================================================
Top Products

   ProductID       Receita
0        782  4.400593e+06
1        783  4.009495e+06
2        779  3.693678e+06
3        780  3.438479e+06
4        781  3.434257e+06

In [9]:
for name, df in datasets.items():
    print(f"{name}: {df.shape}")

Revenue: (1, 1)
Orders: (1, 1)
Average Ticket: (1, 1)
Sales Over Time: (4, 2)
Top Customers: (31465, 3)
Top Products: (266, 2)

In [8]:
datasets = {
    "Revenue": revenue,
    "Orders": orders,
    "Average Ticket": average_ticket,
    "Sales Over Time": sales_over_time,
    "Top Customers": top_customers,
    "Top Products": top_products,
}

In [7]:
revenue = run_query("01_revenue.sql")

orders = run_query("02_orders.sql")

average_ticket = run_query("03_average_ticket.sql")

sales_over_time = run_query("04_sales_over_time.sql")

top_customers = run_query("05_top_customers.sql")

top_products = run_query("06_top_products.sql")

In [6]:
import pandas as pd

from query_executor import run_query

In [5]:
from pathlib import Path
import os

# Volta para a raiz do projeto
os.chdir(Path.cwd().parent)

print(f"Diretório atual: {Path.cwd()}")

Diretório atual: c:\Users\RCFurlan_\Desktop\42\Personal_Misc\Data Portfolio